version: "3"

services:
  dynavins:
    image: dynavins:latest
    build:
        context: ..
        dockerfile: docker/Dockerfile
        args:
            - ROS_DISTRO=melodic
    container_name: dynavins
    privileged: true
    # runtime: nvidia  <- この行を削除

    # ↓↓↓↓ この deploy セクションを丸ごと追加 ↓↓↓↓
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
              
    command: lxterminal
    environment:
        - DISPLAY=$DISPLAY
        - QT_X11_NO_MITSHM=1
        - NVIDIA_VISIBLE_DEVICES=all
        - NVIDIA_DRIVER_CAPABILITIES=all
    devices:
        - /dev/dri
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
        - ../:/root/catkin_ws/src/dynaVINS
        - ~/.Xresources:/root/.Xresources
        # - ~/sandbox_ws/tum_dataset:/root/Dataset
        - ~/.Xauthority:/root/.Xauthority
    network_mode: host
    entrypoint: /root/ros_entrypoint.sh